(() => {
  'use strict';

  const KEYS = { farmers: 'farmers', tokens: 'tokens', currentUser: 'currentUser', mandis: 'mandis', admin: 'adminSession' };
  const defaultMandis = [
    { name: 'Ghaziabad Mandi', prefix: 'GZ', district: 'Ghaziabad', active: true },
    { name: 'Meerut Mandi', prefix: 'MT', district: 'Meerut', active: true },
    { name: 'Delhi Mandi', prefix: 'DL', district: 'Delhi', active: true }
  ];
  const state = { view: 'home', authMode: 'login', adminFilter: 'ALL', lookup: '', lookupResult: null, menuOpen: false };
  const app = document.getElementById('app');
  const toast = document.getElementById('toast');

  function read(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
  function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
  function farmers() { return read(KEYS.farmers, []); }
  function tokens() { return read(KEYS.tokens, []); }
  function mandis() { const value = read(KEYS.mandis, []); if (!value.length) { save(KEYS.mandis, defaultMandis); return defaultMandis; } return value; }
  function currentUser() { return read(KEYS.currentUser, null); }
  function isAdmin() { return localStorage.getItem(KEYS.admin) === 'true'; }
  function uid(prefix) { return prefix + Date.now().toString(36).slice(-6).toUpperCase() + Math.random().toString(36).slice(2, 5).toUpperCase(); }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
  function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 3200); }
  function setView(view) { state.view = view; state.menuOpen = false; render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function activeTokens() { return tokens().filter((token) => ['WAITING', 'CALLED', 'IN PROGRESS'].includes(token.status)); }
  function userTokens() { const user = currentUser(); return user ? tokens().filter((token) => token.farmerId === user.id) : []; }
  function today() { return new Date().toISOString().slice(0, 10); }
  function svg(name, size = 17) { const icons = { leaf: '<path d="M20 4C12 4 5 8 4 20c12-1 16-8 16-16Z"/><path d="M4 20 15 9"/>', arrow: '<path d="m5 12 14 0"/><path d="m13 6 6 6-6 6"/>', shield: '<path d="M12 3 20 7v5c0 5-3.4 8-8 9-4.6-1-8-4-8-9V7l8-4Z"/><path d="m9 12 2 2 4-4"/>', user: '<circle cx="12" cy="8" r="4"/><path d="M4 21c.7-4 3.3-6 8-6s7.3 2 8 6"/>', file: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h5"/>', map: '<path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3-6-3Z"/><path d="M9 3v15M15 6v15"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>', check: '<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>', search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>', menu: '<path d="M4 7h16M4 12h16M4 17h16"/>', close: '<path d="m6 6 12 12M18 6 6 18"/>', phone: '<path d="M7 3h3l2 5-2 2a13 13 0 0 0 4 4l2-2 5 2v3c0 1-1 2-2 2C10 18 5 13 3 4c0-1 1-1 2-1Z"/>', qr: '<path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM15 14h2v2h-2zM18 17h2v3h-3v-2"/>' }; return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${icons[name] || icons.leaf}</svg>`; }
  function button(label, action, kind = '') { return `<button class="button ${kind}" data-action="${action}">${label}</button>`; }
  function status(status) { const className = status.toLowerCase().replaceAll(' ', '-'); return `<span class="status status-${className}">${escapeHtml(status)}</span>`; }

  function header() {
    const logged = currentUser() || isAdmin();
    return `<header class="topbar"><button class="brand" data-action="home"><span class="brand-badge">${svg('leaf', 20)}</span><span class="brand-name">PROCUREX<span class="brand-sub">Digital Procurement Queue System</span></span></button><nav class="nav"><button data-action="home">Home</button><button data-action="how">How it works</button><button data-action="track">Check token</button>${logged ? button('Dashboard', isAdmin() ? 'admin' : 'dashboard', 'outline') : `<button data-action="farmer">Farmer</button><button data-action="admin">Admin</button>`}</nav><button class="menu-button" data-action="toggle-menu" aria-label="Menu">${svg(state.menuOpen ? 'close' : 'menu', 22)}</button>${state.menuOpen ? `<div class="mobile-nav"><button data-action="home">Home</button><button data-action="how">How it works</button><button data-action="track">Check token</button><button data-action="${logged ? (isAdmin() ? 'admin' : 'dashboard') : 'farmer'}">${logged ? 'Dashboard' : 'Farmer portal'}</button></div>` : ''}</header>`;
  }

  function homeView() { return `<main><section class="hero"><div class="hero-copy"><p class="eyebrow">${svg('shield', 16)} Ministry of Consumer Affairs</p><h1>Smart queue management <em>for farmers.</em></h1><p>Get your digital token, track your queue and know when it is your turn at the Mandi.</p><div class="hero-actions">${button('Farmer Portal ' + svg('arrow', 16), 'farmer', 'large')}<button class="text-button" data-action="admin">Admin Portal ${svg('arrow', 16)}</button></div><div class="trust"><span>${svg('check', 14)} Secure farmer records</span><span>${svg('check', 14)} Live status updates</span><span>${svg('check', 14)} Simple and free</span></div></div><div class="hero-panel"><span class="panel-label">TODAY AT A GLANCE</span><div class="big-number">04 <small>min</small></div><p>Average time between queue updates</p><div class="now-serving"><span><i class="dot"></i> Now serving</span><strong>${latestCurrentToken() || 'GZ-097'}</strong><small>Ghaziabad Mandi</small></div></div></section>${howSection()}<section class="lookup-band"><div><p class="eyebrow">Quick lookup</p><h2>Already have a token?</h2><p>Check your position without signing in.</p></div><form class="lookup-form" data-form="lookup"><input name="token" placeholder="Enter token e.g. GZ-101" required><button class="button">Check status ${svg('arrow', 15)}</button></form></section></main>${footer()}`; }
  function howSection() { return `<section class="how" id="how"><p class="eyebrow">One clear process</p><h2>From registration to procurement.</h2><div class="steps">${[['01','Register','Create your farmer profile once.'],['02','Create token','Enter crop and quantity details.'],['03','Track queue','Check your token and live position.'],['04','Visit Mandi','Arrive when your turn is near.']].map(([number, title, copy]) => `<article class="step"><span class="step-number">${number}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div></section>`; }
  function footer() { return `<footer class="footer"><strong>PROCUREX</strong><span>Built for transparent, farmer-friendly procurement.</span></footer>`; }

  function authView(mode) { const register = mode === 'register'; return `<main class="auth-page"><div class="auth-side"><p class="eyebrow">${register ? 'Begin here' : 'Welcome back'}</p><h1>${register ? 'A simpler Mandi day starts here.' : 'Your queue is waiting.'}</h1><p>${register ? 'Create your farmer profile and receive a digital token in minutes.' : 'Use your mobile number and Farmer ID to continue.'}</p></div><form class="form-card" data-form="${register ? 'register' : 'login'}"><div class="form-title"><span class="icon-box">${svg('user', 20)}</span><div><h2>${register ? 'Farmer registration' : 'Farmer login'}</h2><p>${register ? 'All fields are required to create your profile.' : 'Enter the details from your registration.'}</p></div></div>${register ? `<label>Full name<input name="name" required placeholder="e.g. Rahul Kumar"></label><label>Mobile number<input name="mobile" required inputmode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number"></label><label>Village<input name="village" required placeholder="Village name"></label><label>District<input name="district" required placeholder="District"></label><label>State<input name="state" required placeholder="State"></label>` : `<label>Mobile number<input name="mobile" required inputmode="numeric" pattern="[0-9]{10}" placeholder="9876543210"></label><label>Farmer ID<input name="id" required placeholder="FMR001"></label>`}${button(register ? 'Register farmer ' + svg('arrow', 16) : 'Login ' + svg('arrow', 16), '', 'full')}<p class="form-switch">${register ? 'Already registered?' : 'New farmer?'} <button type="button" data-action="${register ? 'login' : 'register'}">${register ? 'Login here' : 'Register here'}</button></p></form></main>`; }

  function dashboardView() { const farmer = currentUser(); const mine = userTokens(); const active = mine.find((token) => ['WAITING','CALLED','IN PROGRESS'].includes(token.status)); const current = active ? mine.find((token) => token.mandi === active.mandi && token.status === 'CALLED') : null; return `<main class="workspace"><div class="workspace-head"><div><p class="eyebrow">Farmer dashboard</p><h1>Welcome, ${escapeHtml(farmer.name.split(' ')[0])}.</h1><p class="muted">Your queue updates are saved in this browser.</p></div>${button('+ Create New Token ' + svg('arrow', 16), 'create', 'large')}</div><div class="metrics"><div class="metric"><span class="metric-icon">${svg('user')}</span><div><label>Farmer ID</label><strong>${escapeHtml(farmer.id)}</strong></div></div><div class="metric"><span class="metric-icon">${svg('file')}</span><div><label>Active token</label><strong>${active ? escapeHtml(active.token) : 'None'}</strong></div></div><div class="metric"><span class="metric-icon">${svg('clock')}</span><div><label>Queue position</label><strong>${active ? '#' + queuePosition(active) : '--'}</strong></div></div><div class="metric"><span class="metric-icon">${svg('map')}</span><div><label>Mandi</label><strong>${active ? escapeHtml(active.mandi) : 'Not selected'}</strong></div></div></div>${active ? tokenCard(active, current) : `<div class="empty"><div class="empty-icon">${svg('file', 21)}</div><h2>No active token</h2><p>Create a token before your Mandi visit to join the queue.</p>${button('Create token ' + svg('arrow', 15), 'create')}</div>`}<div class="quick-links"><button data-action="my-tokens">View My Tokens ${svg('arrow', 15)}</button><button data-action="track">Track a token ${svg('search', 15)}</button><button data-action="profile">View profile ${svg('user', 15)}</button></div><div class="section"><div class="section-title"><div><h2>Recent activity</h2><p class="muted">Your latest saved tokens</p></div><button class="text-button" data-action="my-tokens">View all ${svg('arrow', 14)}</button></div>${mine.slice(0,3).map((token) => `<p><strong>${escapeHtml(token.token)}</strong> · ${escapeHtml(token.product)} · ${status(token.status)}</p>`).join('') || '<p class="muted">No tokens created yet.</p>'}</div></main>`; }

  function tokenCard(token, current) { const mine = currentUser()?.id === token.farmerId; const actions = mine && ['WAITING','CALLED','IN PROGRESS'].includes(token.status) ? `<div class="quick-links"><button data-action="track" data-token="${escapeHtml(token.token)}">Track token ${svg('arrow', 14)}</button><button data-action="cancel-token" data-token="${escapeHtml(token.id)}">Cancel token</button></div>` : ''; return `<section class="token-card"><div><div class="token-top"><span class="eyebrow">Your token</span>${status(token.status)}</div><div class="token-number">${escapeHtml(token.token)}</div><div class="token-mandi">${svg('map', 15)} ${escapeHtml(token.mandi)}</div><div class="token-details"><div><small>Product</small><strong>${escapeHtml(token.product)}</strong></div><div><small>Quantity</small><strong>${escapeHtml(token.quantity)} ${escapeHtml(token.unit)}</strong></div><div><small>Queue position</small><strong>#${queuePosition(token)}</strong></div><div><small>Current token</small><strong>${current ? escapeHtml(current.token) : latestForMandi(token.mandi) || '--'}</strong></div></div>${token.status === 'CALLED' ? `<div class="called">${svg('check', 18)} Your turn has been called. Please proceed to the procurement desk.</div>` : ''}${actions}</div><div class="qr-box"><div class="qr-code" data-qr="${escapeHtml(token.token)}"></div><small>Scan to verify token</small><button class="text-button" data-action="download-qr" data-token="${escapeHtml(token.token)}">${svg('qr', 14)} Download QR</button></div></section>`; }

  function createView() { return `<main class="workspace narrow"><div class="workspace-head"><div><p class="eyebrow">New queue entry</p><h1>Create a procurement token.</h1><p class="muted">Share your crop details once. We will keep your place updated.</p></div></div><form class="form-card" data-form="create"><div class="form-section"><h3>Mandi details</h3><div class="field-grid"><label>Select Mandi<select name="mandi" required><option value="">Choose a Mandi</option>${mandis().filter((item) => item.active).map((item) => `<option value="${escapeHtml(item.name)}">${escapeHtml(item.name)} · ${escapeHtml(item.district)}</option>`).join('')}</select></label><label>Visit date<input type="date" name="date" min="${today()}" value="${today()}" required></label></div></div><div class="form-section"><h3>Product details</h3><div class="field-grid"><label>Product / crop<select name="product" required><option value="">Choose a crop</option><option>Wheat</option><option>Rice</option><option>Potato</option><option>Mustard</option><option>Other</option></select></label><label>Quantity<input name="quantity" type="number" min="1" step="any" required placeholder="25"></label><label>Unit<select name="unit"><option>Quintal</option><option>Kg</option><option>Ton</option></select></label><label>Vehicle number <span class="muted">optional</span><input name="vehicle" placeholder="UP14 AB 1234"></label></div></div><button class="button full">Generate Token ${svg('arrow', 16)}</button></form></main>`; }

  function profileView() { const farmer = currentUser(); return `<main class="workspace narrow"><div class="workspace-head"><div><p class="eyebrow">Farmer profile</p><h1>Your details.</h1><p class="muted">This information is stored locally for your presentation demo.</p></div></div><section class="section"><div class="metrics">${[['Farmer ID', farmer.id],['Name', farmer.name],['Mobile', farmer.mobile],['Village', farmer.village],['District', farmer.district],['State', farmer.state]].map(([label, value]) => `<div class="metric"><div><label>${label}</label><strong>${escapeHtml(value)}</strong></div></div>`).join('')}</div><button class="button outline" data-action="logout">Logout farmer</button></section></main>`; }

  function myTokensView() { const mine = userTokens(); return `<main class="workspace"><div class="workspace-head"><div><p class="eyebrow">Your records</p><h1>My tokens.</h1><p class="muted">All your saved queue entries.</p></div>${button('Create new token ' + svg('arrow', 15), 'create')}</div><div class="table-wrap"><table class="table"><thead><tr><th>Token</th><th>Mandi</th><th>Product</th><th>Quantity</th><th>Date</th><th>Status</th></tr></thead><tbody>${mine.length ? mine.map((token) => `<tr><td><strong>${escapeHtml(token.token)}</strong></td><td>${escapeHtml(token.mandi)}</td><td>${escapeHtml(token.product)}</td><td>${escapeHtml(token.quantity)} ${escapeHtml(token.unit)}</td><td>${escapeHtml(token.date)}</td><td>${status(token.status)}</td></tr>`).join('') : `<tr><td colspan="6"><div class="empty"><h2>No tokens found</h2><p>Your active and completed tokens will appear here.</p></div></td></tr>`}</tbody></table></div></main>`; }

  function trackView() { const token = state.lookupResult; return `<main class="track"><div><p class="eyebrow">Public token lookup</p><h1>Check your queue status.</h1><p class="muted">Enter a token number to see its public status.</p></div><form class="search-card" data-form="lookup"><div class="search-grid"><label>Token number<input name="token" value="${escapeHtml(state.lookup)}" placeholder="e.g. GZ-101" required></label><label>Mobile number <span class="muted">optional</span><input name="mobile" placeholder="10-digit number"></label></div><button class="button" style="margin-top:16px">Check status ${svg('search', 15)}</button></form>${state.lookup ? token ? `<div class="track-result">${tokenCard(token, null)}</div>` : `<div class="not-found">${svg('search', 20)} No matching token found. Check the token number and try again.</div>` : ''}</main>`; }

  function adminView() { const list = tokens(); const filtered = state.adminFilter === 'ALL' ? list : list.filter((token) => token.status === state.adminFilter); return `<main class="workspace"><div class="workspace-head"><div><p class="eyebrow">Operations desk</p><h1>Queue control room.</h1><p class="muted">Monitor every Mandi and keep farmers moving.</p></div><span class="admin-tag">${svg('shield', 16)} Admin verified</span></div><div class="metrics"><div class="metric"><span class="metric-icon">${svg('user')}</span><div><label>Total farmers</label><strong>${farmers().length}</strong></div></div><div class="metric"><span class="metric-icon">${svg('file')}</span><div><label>Today's tokens</label><strong>${list.filter((token) => token.date === today()).length}</strong></div></div><div class="metric"><span class="metric-icon">${svg('clock')}</span><div><label>Waiting</label><strong>${list.filter((token) => token.status === 'WAITING').length}</strong></div></div><div class="metric"><span class="metric-icon">${svg('check')}</span><div><label>Completed</label><strong>${list.filter((token) => token.status === 'COMPLETED').length}</strong></div></div></div><div class="mandi-grid">${mandis().map((mandi) => `<div class="mandi-card"><div><strong>${escapeHtml(mandi.name)}</strong><small>${activeTokens().filter((token) => token.mandi === mandi.name).length} active in queue</small></div><button class="button outline" data-action="call-next" data-mandi="${escapeHtml(mandi.name)}">Call next ${svg('arrow', 14)}</button></div>`).join('')}</div><div class="toolbar"><div><h2>Token management</h2><p class="muted">Changes update every open tab.</p></div><select data-control="admin-filter"><option value="ALL" ${state.adminFilter === 'ALL' ? 'selected' : ''}>All statuses</option>${['WAITING','CALLED','IN PROGRESS','COMPLETED','SKIPPED','CANCELLED'].map((item) => `<option ${state.adminFilter === item ? 'selected' : ''}>${item}</option>`).join('')}</select></div><div class="table-wrap"><table class="table"><thead><tr><th>Token</th><th>Farmer</th><th>Product</th><th>Mandi</th><th>Status</th><th>Action</th></tr></thead><tbody>${filtered.length ? filtered.map(adminRow).join('') : '<tr><td colspan="6"><div class="empty"><h2>No tokens found</h2><p>Create a farmer token to see it here.</p></div></td></tr>'}</tbody></table></div><div class="quick-links"><button data-action="load-demo">Load Demo Data ${svg('arrow', 15)}</button><button data-action="clear-demo">Clear Demo Data</button><button data-action="logout">Logout admin</button></div></main>`; }
  function adminRow(token) { const actions = token.status === 'WAITING' ? `<button data-action="transition" data-token="${token.id}" data-next="CALLED">Call</button>` : token.status === 'CALLED' ? `<button data-action="transition" data-token="${token.id}" data-next="IN PROGRESS">Start</button>` : token.status === 'IN PROGRESS' ? `<button data-action="transition" data-token="${token.id}" data-next="COMPLETED">Complete</button>` : ''; const cancel = ['WAITING','CALLED'].includes(token.status) ? `<button class="danger" data-action="transition" data-token="${token.id}" data-next="CANCELLED">Cancel</button>` : ''; return `<tr><td><strong>${escapeHtml(token.token)}</strong><small>${escapeHtml(token.date)}</small></td><td>${escapeHtml(token.farmerName)}<small>${escapeHtml(token.mobile)}</small></td><td>${escapeHtml(token.product)}<small>${escapeHtml(token.quantity)} ${escapeHtml(token.unit)}</small></td><td>${escapeHtml(token.mandi)}</td><td>${status(token.status)}</td><td class="action-row">${actions}${cancel}</td></tr>`; }

  function queuePosition(token) { return activeTokens().filter((item) => item.mandi === token.mandi && item.date === token.date).sort((a, b) => a.createdAt - b.createdAt).findIndex((item) => item.id === token.id) + 1; }
  function latestForMandi(mandi) { const current = activeTokens().filter((token) => token.mandi === mandi).find((token) => ['CALLED','IN PROGRESS'].includes(token.status)); return current ? current.token : null; }
  function latestCurrentToken() { const current = activeTokens().find((token) => ['CALLED','IN PROGRESS'].includes(token.status)); return current ? current.token : null; }
  function prefixFor(mandi) { return mandis().find((item) => item.name === mandi)?.prefix || 'M'; }
  function render() { let content = state.view === 'home' ? homeView() : state.view === 'login' ? authView('login') : state.view === 'register' ? authView('register') : state.view === 'dashboard' ? dashboardView() : state.view === 'create' ? createView() : state.view === 'profile' ? profileView() : state.view === 'my-tokens' ? myTokensView() : state.view === 'track' ? trackView() : state.view === 'admin' ? adminView() : homeView(); app.innerHTML = `<div class="app">${header()}${content}</div>`; drawQrs(); }

  function drawQrs() { document.querySelectorAll('[data-qr]').forEach((element) => { const token = element.dataset.qr; let seed = 0; for (const char of token) seed = (seed * 31 + char.charCodeAt(0)) % 997; let cells = ''; for (let row = 0; row < 15; row++) for (let col = 0; col < 15; col++) { const corner = (row < 5 && col < 5) || (row < 5 && col > 9) || (row > 9 && col < 5); const finder = corner && ((row % 4 === 0 || row % 4 === 4 || col % 4 === 0 || col % 4 === 4) || (row % 4 > 0 && row % 4 < 4 && col % 4 > 0 && col % 4 < 4)); const dark = finder || ((seed + row * 17 + col * 29 + row * col) % 5 < 2); if (dark) cells += `<i style="left:${col * 6.666}%;top:${row * 6.666}%"></i>`; } element.innerHTML = `<span class="qr-grid">${cells}</span>`; }); }

  function register(form) { const data = Object.fromEntries(new FormData(form)); const mobile = String(data.mobile).replace(/\D/g, ''); if (!/^\d{10}$/.test(mobile)) return showToast('Enter a valid 10-digit mobile number.'); if (farmers().some((farmer) => farmer.mobile === mobile)) return showToast('This mobile number is already registered.'); const farmer = { id: 'FMR' + String(farmers().length + 1).padStart(3, '0'), name: String(data.name).trim(), mobile, village: String(data.village).trim(), district: String(data.district).trim(), state: String(data.state).trim(), createdAt: Date.now() }; save(KEYS.farmers, [...farmers(), farmer]); save(KEYS.currentUser, farmer); showToast('Registration successful!'); setView('dashboard'); }
  function login(form) { const data = Object.fromEntries(new FormData(form)); const farmer = farmers().find((item) => item.mobile === String(data.mobile).replace(/\D/g, '') && item.id.toUpperCase() === String(data.id).trim().toUpperCase()); if (!farmer) return showToast('Farmer not found. Please register first.'); save(KEYS.currentUser, farmer); setView('dashboard'); }
  function createToken(form) { const data = Object.fromEntries(new FormData(form)); const user = currentUser(); if (!user) return setView('login'); if (!data.mandi || !data.product || !data.quantity || Number(data.quantity) <= 0) return showToast('Please complete the Mandi, crop and quantity fields.'); const list = tokens(); const mandi = mandis().find((item) => item.name === data.mandi); const sameMandi = list.filter((item) => item.mandi === data.mandi); const next = Math.max(100, ...sameMandi.map((item) => Number(item.token.replace(mandi.prefix + '-', '')) || 100)) + 1; const duplicateActive = list.some((item) => item.farmerId === user.id && ['WAITING','CALLED','IN PROGRESS'].includes(item.status)); if (duplicateActive) return showToast('You already have an active token.'); const token = { id: uid('TKN'), token: `${mandi.prefix}-${next}`, farmerId: user.id, farmerName: user.name, mobile: user.mobile, mandi: data.mandi, product: data.product, quantity: Number(data.quantity), unit: data.unit, vehicle: data.vehicle || '', date: data.date || today(), status: 'WAITING', createdAt: Date.now() }; save(KEYS.tokens, [...list, token]); showToast(`Token ${token.token} generated successfully.`); setView('dashboard'); }
  function transition(id, next) { const list = tokens(); const token = list.find((item) => item.id === id); if (!token) return; if (next === 'CALLED' && list.some((item) => item.mandi === token.mandi && ['CALLED','IN PROGRESS'].includes(item.status))) return showToast('Finish the current procurement before calling another farmer.'); token.status = next; token.updatedAt = Date.now(); save(KEYS.tokens, list); showToast(`${token.token} is now ${next}.`); render(); }
  function callNext(mandi) { const next = activeTokens().filter((token) => token.mandi === mandi && token.status === 'WAITING').sort((a, b) => a.createdAt - b.createdAt)[0]; if (!next) return showToast('No waiting farmers in this Mandi.'); transition(next.id, 'CALLED'); }
  function loadDemo() { const sampleFarmers = [{ id: 'FMR001', name: 'Rahul Kumar', mobile: '9876543210', village: 'Muradnagar', district: 'Ghaziabad', state: 'Uttar Pradesh', createdAt: Date.now(), demo: true }, { id: 'FMR002', name: 'Sita Devi', mobile: '9876543211', village: 'Modinagar', district: 'Ghaziabad', state: 'Uttar Pradesh', createdAt: Date.now(), demo: true }]; const existing = farmers(); sampleFarmers.forEach((item) => { if (!existing.some((farmer) => farmer.id === item.id)) existing.push(item); }); save(KEYS.farmers, existing); const existingTokens = tokens(); [{ token: 'GZ-101', farmerId: 'FMR001', farmerName: 'Rahul Kumar', mobile: '9876543210', mandi: 'Ghaziabad Mandi', product: 'Wheat', quantity: 25, unit: 'Quintal', date: today(), status: 'WAITING' }, { token: 'GZ-102', farmerId: 'FMR002', farmerName: 'Sita Devi', mobile: '9876543211', mandi: 'Ghaziabad Mandi', product: 'Rice', quantity: 15, unit: 'Quintal', date: today(), status: 'WAITING' }].forEach((sample, index) => { if (!existingTokens.some((token) => token.token === sample.token)) existingTokens.push({ ...sample, id: uid('TKN'), createdAt: Date.now() + index, demo: true }); }); save(KEYS.tokens, existingTokens); showToast('Demo data loaded.'); render(); }
  function clearDemo() { save(KEYS.farmers, farmers().filter((farmer) => !farmer.demo)); save(KEYS.tokens, tokens().filter((token) => !token.demo)); showToast('Demo data cleared. Manual records were kept.'); render(); }
  function cancelToken(id) { const list = tokens(); const token = list.find((item) => item.id === id && item.farmerId === currentUser()?.id); if (!token) return; if (!['WAITING','CALLED'].includes(token.status)) return showToast('This token can no longer be cancelled.'); token.status = 'CANCELLED'; token.updatedAt = Date.now(); save(KEYS.tokens, list); showToast(`${token.token} cancelled.`); render(); }
  function logout() { localStorage.removeItem(KEYS.currentUser); localStorage.removeItem(KEYS.admin); setView('home'); showToast('You have been logged out.'); }

  app.addEventListener('click', (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const action = target.dataset.action; if (action === 'home') setView('home'); else if (action === 'how') { setView('home'); setTimeout(() => document.getElementById('how')?.scrollIntoView({ behavior: 'smooth' }), 50); } else if (action === 'farmer') setView(currentUser() ? 'dashboard' : 'login'); else if (action === 'register') setView('register'); else if (action === 'login') setView('login'); else if (action === 'admin') setView('admin-login'); else if (action === 'dashboard') setView('dashboard'); else if (action === 'create') setView('create'); else if (action === 'track') { state.lookup = target.dataset.token || ''; setView('track'); } else if (action === 'profile') setView('profile'); else if (action === 'my-tokens') setView('my-tokens'); else if (action === 'toggle-menu') { state.menuOpen = !state.menuOpen; render(); } else if (action === 'logout') logout(); else if (action === 'call-next') callNext(target.dataset.mandi); else if (action === 'transition') transition(target.dataset.token, target.dataset.next); else if (action === 'load-demo') loadDemo(); else if (action === 'clear-demo') clearDemo(); else if (action === 'cancel-token') cancelToken(target.dataset.token); else if (action === 'download-qr') showToast('QR image is ready for your presentation.'); });
  document.addEventListener('submit', (event) => { const form = event.target; if (!(form instanceof HTMLFormElement)) return; event.preventDefault(); if (form.dataset.form === 'register') register(form); else if (form.dataset.form === 'login') login(form); else if (form.dataset.form === 'create') createToken(form); else if (form.dataset.form === 'lookup') { const data = Object.fromEntries(new FormData(form)); state.lookup = String(data.token).trim().toUpperCase(); state.lookupResult = tokens().find((token) => token.token.toUpperCase() === state.lookup && (!data.mobile || token.mobile === data.mobile)) || null; setView('track'); } else if (form.dataset.form === 'admin-login') { const data = Object.fromEntries(new FormData(form)); if (data.username === 'admin' && data.password === 'admin123') { localStorage.setItem(KEYS.admin, 'true'); setView('admin'); } else showToast('Invalid admin credentials. Try admin / admin123.'); } });
  document.addEventListener('change', (event) => { const target = event.target; if (target.matches('[data-control="admin-filter"]')) { state.adminFilter = target.value; render(); } });
  window.addEventListener('storage', () => render());

  const oldAdmin = adminView; // Keep admin login as a small view beside the main dashboard.
  function adminLoginView() { return `<main class="auth-page"><div class="auth-side"><p class="eyebrow">Authorized access</p><h1>Keep the queue moving.</h1><p>Admin tools for calling, starting and completing farmer procurements.</p></div><form class="form-card" data-form="admin-login"><div class="form-title"><span class="icon-box">${svg('shield', 20)}</span><div><h2>Admin portal</h2><p>Demo credentials are provided for presentation use.</p></div></div><label>Username<input name="username" required placeholder="admin"></label><label>Password<input name="password" required type="password" placeholder="admin123"></label>${button('Open admin dashboard ' + svg('arrow', 16), '', 'full')}<p class="form-switch">Demo login: <strong>admin / admin123</strong></p></form></main>`; }
  const originalRender = render;
  render = function renderWithAdminLogin() { if (state.view === 'admin-login') { app.innerHTML = `<div class="app">${header()}${adminLoginView()}</div>`; return; } originalRender(); };
  mandis();
  render();
})();
